# railway.toml

name = "Gemini_Discord_Bot"
language = "python"
output = "python310"

[[services]]
  name = "discord-bot"
  script = "GeminiDiscordBot.py"
  port = 3000  # Replace with the appropriate port if needed

[env]
  RAILWAY_ENV = "production"

[start]
  command = "echo 'No start command required'"